name: Checkout pyprecag on Windows. Build html documents from pyprecag and commit any updates.

on: 
    push:
    schedule: ## Schedule to run at midnight
    - cron: '0 0 * * *'


jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH


    - name: Install dependencies
      run: |
        C:\Miniconda\condabin\conda.bat env update --file environment.yml --name base
        C:\Miniconda\condabin\conda.bat init powershell
    - name: Lint with flake8
      run: |
        # Activate the base environment
        C:\Miniconda\condabin\conda.bat activate base
        C:\Miniconda\condabin\conda.bat install flake8
        C:\Miniconda\condabin\conda.bat install gdal
        C:\Miniconda\condabin\conda.bat install fiona
        C:\Miniconda\condabin\conda.bat install geopandas
        #conda install fiona
        #conda install geopandas        

    - name: Install dependencies
      run: |
        conda install gdal
        conda install fiona
        conda install geopandas
        conda install sphinx
        conda install sphinx_rtd_theme
    - name: Checkout latest pyprecag
      run: |
        echo "Do a git checkout of the latest mnbMerge2Maint branch of pyprecag"
        cd ..
        git clone -b mnbMerge2Maint --single-branch --depth 1 https://github.com/CSIRO-Precision-Agriculture/pyprecag.git
        cd pyprecag
        pip install .
    - name: Use Sphinx to build html docs from pyprecag source code
      run: |
        cd ../pyprecag
        make html
    - name: Check and compare html docs
      run: |
        cd ..        
        echo "List pyprecag/build/docs html files"
        ls ./pyprecag/build/docs/html
        echo "List pyprecag_docs html files"
        ls ./pyprecag_docs
    - name: Attempt to overwrite html files
      run: |
        echo "git remove"
        git rm -r *
        cd ..        
        echo "List pyprecag_docs html files"
        ls ./pyprecag_docs
        echo "Copy"
        Copy-Item -Path .\pyprecag\build\docs\html\* -Recurse -Destination .\pyprecag_docs -Verbos
        echo "List pyprecag_docs html files"
        ls ./pyprecag_docs
        echo "Call a git diff"
        cd pyprecag_docs
        #git diff > diff.log
        echo "Call a git add -all"
        git add --all
        echo "Call a git commit -all"
        git commit -all
        dir
    - name: Upload diff.log file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact.log
        path: .\pyprecag_docs\diff.log
